/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javanhan_vien;

import java.awt.Color;

/**
 *
 * @author ADMIN
 */
public class AddStaffForm extends javax.swing.JFrame {

    /**
     * Creates new form NewJFramenhan_vien1
     */
    public AddStaffForm() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtStaffid1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaNote1 = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        txtFullname1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btnCreate1 = new javax.swing.JButton();
        cbxCountry1 = new javax.swing.JComboBox<>();
        btnUpdate1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        btnDelete1 = new javax.swing.JButton();
        rdbMale1 = new javax.swing.JRadioButton();
        btnReset1 = new javax.swing.JButton();
        rdbFemale1 = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        chkSingle1 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Staff ID");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 79, -1));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Note");
        jPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 37, -1));

        txtStaffid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStaffid1ActionPerformed(evt);
            }
        });
        jPanel8.add(txtStaffid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 160, 630, -1));

        txaNote1.setColumns(20);
        txaNote1.setRows(5);
        jScrollPane2.setViewportView(txaNote1);

        jPanel8.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 630, 160));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Fullname");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));
        jPanel8.add(txtFullname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 110, 630, -1));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Country");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        btnCreate1.setText("Create");
        btnCreate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreate1ActionPerformed(evt);
            }
        });
        jPanel8.add(btnCreate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, -1, -1));

        cbxCountry1.setForeground(new java.awt.Color(255, 255, 255));
        cbxCountry1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "       Việt Nam", "Mỹ", "Tây Ban Nha", "Zimbabwe" }));
        cbxCountry1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCountry1ActionPerformed(evt);
            }
        });
        jPanel8.add(cbxCountry1, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 210, 630, -1));

        btnUpdate1.setText("Update");
        jPanel8.add(btnUpdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, -1, -1));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Gender");
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 41, -1));

        btnDelete1.setText("Delete");
        jPanel8.add(btnDelete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 500, -1, -1));

        rdbMale1.setForeground(new java.awt.Color(255, 255, 255));
        rdbMale1.setText("Male");
        rdbMale1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbMale1ActionPerformed(evt);
            }
        });
        jPanel8.add(rdbMale1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 98, -1));

        btnReset1.setText("Reset");
        jPanel8.add(btnReset1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 500, -1, -1));

        rdbFemale1.setForeground(new java.awt.Color(255, 255, 255));
        rdbFemale1.setText("Female");
        rdbFemale1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbFemale1ActionPerformed(evt);
            }
        });
        jPanel8.add(rdbFemale1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 98, -1));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Status");
        jPanel8.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 37, -1));

        chkSingle1.setForeground(new java.awt.Color(255, 255, 255));
        chkSingle1.setText("Single");
        chkSingle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSingle1ActionPerformed(evt);
            }
        });
        jPanel8.add(chkSingle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 85, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\OneDrive\\Máy tính\\Đồ Án\\image 5.png")); // NOI18N
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\OneDrive\\Máy tính\\Đồ Án\\image 4.png")); // NOI18N
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 400, 110, 140));

        jLabel1.setBackground(new Color(0, 0, 0, 0));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Phone Number");
        jPanel8.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));
        jPanel8.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 630, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\OneDrive\\Máy tính\\Đồ Án\\image 3.png")); // NOI18N
        jPanel8.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\OneDrive\\Máy tính\\Đồ Án\\Frame 1.png")); // NOI18N
        jPanel8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, -1));

        jLabel4.setText("jLabel4");
        jPanel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtStaffid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStaffid1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStaffid1ActionPerformed

    private void btnCreate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreate1ActionPerformed

    private void cbxCountry1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCountry1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCountry1ActionPerformed

    private void rdbMale1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbMale1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbMale1ActionPerformed

    private void rdbFemale1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbFemale1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbFemale1ActionPerformed

    private void chkSingle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSingle1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkSingle1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStaffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStaffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStaffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStaffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStaffForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate1;
    private javax.swing.JButton btnDelete1;
    private javax.swing.JButton btnReset1;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxCountry1;
    private javax.swing.JCheckBox chkSingle1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton rdbFemale1;
    private javax.swing.JRadioButton rdbMale1;
    private javax.swing.JTextArea txaNote1;
    private javax.swing.JTextField txtFullname1;
    private javax.swing.JTextField txtStaffid1;
    // End of variables declaration//GEN-END:variables
}
